### ISSUE TITLE
.package-lock vs .yarn-lock

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#15]
Right now the resolved module dependency tree is described in both `.yarn-lock` (when building with Yarn) and `.package-lock` (when building with npm).

Can both be synchronized? How to make sure these are kept up-to-date?

**Comment by danielweck** [comment]
In other NodeJS projects I personally have used Yarn on my development machine for a long time (instead of NPM), but more recently I have had to maintain the NPM lockfile too for developers who rely on it.
Unfortunately in practice Yarn and NPM are mutually-exclusive, due to inconsistencies in the `node_modules` folder and  the global package cache.
..so, I use a separate development machine with NPM only (so that Yarn cannot possibly interfere in my dual Yarn-NPM build scripts), and that's where I update the NPM lockfile from (admittedly, less frequently than Yarn lock file).
An important point is continuous integration, in my case: TravisCI uses Yarn (not NPM) to build the project, run the tests, and deploy to the app servers. Therefore every time code is pushed by a developer to the source repository, we need to make sure that `yarn upgrade` is invoked, so that the lockfile is committed and consistent between the developer's machine and the remote build server.

**Comment by rdeltour** [comment]
thanks for sharing your experience @danielweck! 😄

**Comment by rdeltour** [comment]
I would be in favor of ignoring `.package-lock` altogether, and stating that we only officially support Yarn for development (several scripts are invoking yarn anyways).

If people want to use npm for their daily dev, they can keep a package lock of their own (for instance in a fork).

Would that work for your @marisademeglio ?

**Comment by marisademeglio** [comment]
Fine w me!

**Comment by danielweck** [comment]
Personal feedback: in several of our NodeJS projects we have moved away from Yarn, and back to NPM now that there is better performance (caching) and integrity verification. We have also come across severe bugs in Yarn so we got fed up with it. So, we now primarily use NPM, but in some projects we still support Yarn (both lock files in the source tree) because of legacy needs.
PS: `yarn install` and `upgrade` are the most important commands (with discrepancies in the node_modules dependency tree compared with NPM), but `yarn run xxx` is near-equivalent to `npm run xxx` (unless you are dealing with edge-case native makefiles / env vars), so my advice would be to stick to `npm run xxx` in your package.json, even if you are recommending Yarn (yarn.lock).
