### ISSUE TITLE
Table issues are ignored

### ISSUE THREAD

**Issue by gregoriopellegrino** [daisy/ace#186]
Ace version 1.0.0
Node version 8.7.0
MacOs 10.12.6

Some table issues aren't reported. For example:

- tables with only one row
- tables with no table-heads
- tables with empty cells

Here you can find an example file:
[table_test.epub.zip](https://github.com/daisy/ace/files/2036043/table_test.epub.zip)

Gregorio

**Comment by rdeltour** [comment]
Thanks for the report and the sample file 👍

 >  tables with only one row
 >  tables with empty cells

I don’t think these are accessibility issues. Which accessibility requirement are you thinking about?

 >  tables with no table-heads

aXe can check that a data cell has an associated header with the `td-has-header` rule, however this rule is disabled by default (it’s tagged "experimental") and only applies to tables larger than 3x3.

A future version of Ace will allow customizing the rule set used to configure aXe; this will allow to enable the `td-has-header` rule mentioned above.

**Comment by gregoriopellegrino** [comment]
Good for the `td-has-header` rule.

For:
- tables with only one row
- tables with empty cells

Usually the problem is that these kind of tables are used for layout design, but a check can find false-positive issues, so no absolute way to check them.

**Cross checking**
I've done some tests with a single-row-table with Word accessibility checker and Acrobat Pro accessibility checker:
- Word for Mac exports single-row-tables as paragraphs and not as tables
- Acrobat Pro returns an error on single-row-tables, because they don't have a heading row (https://helpx.adobe.com/in/acrobat/using/create-verify-pdf-accessibility.html#TableHeaders)

**Comment by mattgarrish** [comment]
Using tables for layouts is discouraged but not a violation of WCAG.

The requirements for layout tables is that they not employ any semantic tags (th, caption, summary) so that AT don't interpret them as data tables, and that the content makes sense when linearized:

- https://www.w3.org/TR/WCAG20-TECHS/F46.html
- https://www.w3.org/TR/WCAG20-TECHS/F49.html

These can only ever be checked reliably by a human, so getting ace to flag suspect tables would be problematic. A single-row table that has semantic markup would probably be more of a warning sign than just a single-row table.

**Comment by rdeltour** [comment]
Closing this issue as "won't fix". @gregoriopellegrino feel free to continue the discussion or reopen if you consider Ace should do something else.
