### ISSUE TITLE
ace-cli as stand-alone executable?

### ISSUE THREAD

**Issue by hatton** [daisy/ace#190]
Has anyone packaged ace-cli as a standalone executable? We would like to bundle this with our non-nodejs application; i.e. the user will  not have node installed.

I've been defeated thus far by [pkg](https://www.npmjs.com/package/pkg) & [nexe](https://www.npmjs.com/package/nexe)...

**Comment by rdeltour** [comment]
last time I tried, I wasn't able either to build a standalone executable. The primary reason I guess is the integration of Chromium, which makes it much more complex than for "simple" JS-only node modules.

We decided that we will work on a minimal GUI for the folks that are not familiar with `npm` or `yarn`, but if anyone is interested in pursuing the experiments with building a standalone executable CLI tool, I’d be happy to help or follow the experiments in whatever way I can!

(I’m closing this as `wontfix`, but feel free to keep on commenting here, or ping us at ace@daisy.org)

**Comment by acabal** [comment]
Chiming in here to say this would be very useful. We would like to bundle it in the Standard Ebooks toolset to add automated accessibility checking. It would be very nice to be able to simply bundle an executable with our tools like we do with epubcheck, instead of asking the user to install nodejs on their system and then do additional command line incantations to install Ace.

**Comment by danielweck** [comment]
Hi Alex, just out of interest, what operating systems do you need the binary executable for? (Windows, Mac, Linux?)

**Comment by acabal** [comment]
Most of the people using our toolset use Linux or Mac. There are some Windows users using the Linux compatibility layer who have gotten things to work but it's not officially supported. I believe `pkg` can build binaries for all 3 platforms?

**Comment by danielweck** [comment]
> I believe `pkg` can build binaries for all 3 platforms?

Yes, https://github.com/vercel/pkg works great for this ... but Ace relies on Puppeteer (internally, Chromium), or alternatively Electron (also Chromium-based, but ships with its own NodeJS runtime). In both cases, "bundling" the correct platform-specific binary dependencies in a standalone executable is technically tricky. Ace validates EPUB publications by launching a fixed-size pool of web browser rendering contexts (each webview loads a single XHTML content document), all from a single NodeJS process. I haven't explored this problem space lately, but last time I looked it was quite a pain due to the interaction with Puppeteer / Electron.
CC @marisademeglio
