### ISSUE TITLE
Rule epub-type-has-matching-role

### ISSUE THREAD

**Issue by johnlourdusamy** [daisy/ace#214]
ACE validator validates if an element has an ARIA role matching its epub:type.
However it does not validate role attribute according to the HTML elements referred in ARIA in HTML (https://www.w3.org/TR/html-aria/) spec.

**Comment by laudrain** [comment]
So according to EPUBCheck 4.2.0, the proper coding for epub:type and ARIA role for the cover would be :
```
    <body class="bodypp" lang="fr" xml:lang="fr" epub:type="cover">
        <section  class="sectionpp" epub:type="cover">
            <a id="cover"><img src="cover/cover.jpg"
                    alt="Couverture : Mercedes Ron, À contre-sens (2. Nick), Hachette Jeunesse"
                    class="imgpp" role="doc-cover"/></a>
        </section>
    </body>

```
Here epub:type `cover` is placed according to [EPUB 3 Structural Semantics Vocabulary](https://idpf.github.io/epub-vocabs/structure/#cover) contexts: `body` or `section`. 
And  according ARIA in HTML (https://www.w3.org/TR/html-aria/), role `doc-cover` is in the `img` tag.

The issue is with **Ace reporting an error of "Element has no ARIA role matching its epub:type"** in `body` and `section`.

**Comment by clapierre** [comment]
`<body class="bodypp" lang="fr" xml:lang="fr" epub:type="cover">` 

Really?  I thought body should never have a class, type, or even the languages right?
Shouldn't it always be just
` <body>`

**Comment by laudrain** [comment]
@clapierre `body` can have all the common attributes:
[https://www.w3.org/TR/2010/WD-html-markup-20100304/common-attributes.html](https://www.w3.org/TR/2010/WD-html-markup-20100304/common-attributes.html)

**Comment by clapierre** [comment]
Thanks @laudrain
