### ISSUE TITLE
'Best practice' ruleset isn't the 'bestest'

### ISSUE THREAD

**Issue by garconvacher** [daisy/ace#220]
Hi,

This is a side effect from Epubcheck 4.2.
@mattgarrish gave [a good advice](https://github.com/w3c/epubcheck/issues/965#issuecomment-461387988) about using ARIA roles properly. So I removed roles in the links inside `<nav epub:type="landmarks">`. Logically, ACE warns about this : _Element has no ARIA role matching its epub:type_

**Comment by mattgarrish** [comment]
Right, I don't believe Ace distinguishes the specialized lists defined in the navigation document, and because epubcheck isn't currently validating role usage it will introduce conflicts that will then be exposed by the new version of epubcheck.

A good start at tuning down Ace might be to ignore any use of epub:type inside of `nav` elements, as I believe that's where EPUB really went astray from ARIA. Whether epub:type is used on the list items or on the `a` tags, it's typically being used to convey what structure is at the end of the link, whereas roles change the nature of the element.
