### ISSUE TITLE
HTML Report in Firefox: links in tabs are inactive

### ISSUE THREAD

**Issue by garconvacher** [daisy/ace#277]
Hi,

In the HTML Report with ACE 1.1.1, links in other tabs than the default "Violations" don't work in Firefox 68. Works fine in Chrome and Edge.

Please provide the following details if possible or relevant:

- [x] **1.1.1** the version of Ace impacted by the issue (as returned by the `ace -v` command).
- [x] 11.1.0 the version of Node used to run Ace (as returned by the `node -v` command).
- [x] W10 1903 your operating system and version.
- [] if the issue is a bug when running Ace: the error message as produced in the log file (you can enable debug logging with the `--verbose` option).
- [x] if the issue is about the HTML report: the browser(s) and version(s) you used. **Firefox 68.0.2**
- [] if possible, let us know if you can share a sample input file to help us reproduce the issue.

**Comment by garconvacher** [comment]
Weird... Works fine in Firefox now. I close the issue :/

**Comment by garconvacher** [comment]
Don't work again... It seems to appear randomly.
In Firefox's console, I read several errors and warnings. Full log in this file : [Log_Firefox.txt](https://github.com/daisy/ace/files/3546649/Log_Firefox.txt)

(Chrome and Edge still OK)

**Comment by danielweck** [comment]
Probable culprit: the HTML report is currently not purely an offline document, it needs to connect to the web in order to apply Javascript and CSS (in order to enable the rich report rendering / interaction features). As a result, loading the `report.html` from `file://` instead of a web server / HTTP URL is cause for various CORS warnings / errors.

https://github.com/daisy/ace/blob/5d4cc866af8141180980522748c0aa82830afb7a/packages/ace-report/src/report-template.handlebars#L4-L5

https://github.com/daisy/ace/blob/5d4cc866af8141180980522748c0aa82830afb7a/packages/ace-report/src/report-template.handlebars#L459-L463

**Comment by danielweck** [comment]
I filed a separate issue so the Ace dev team can investigate the feasibility of "offline-ing" the HTML report entirely:
https://github.com/daisy/ace/issues/278

I propose we keep this current issue open, just in case we find a more lightweight workaround for Firefox.

**Comment by danielweck** [comment]
This was fixed in a recent Ace release. Dependencies (CSS and JavaScript) are now shipped with / alongside the HTML report.
