### ISSUE TITLE
ace.log locked

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#284]
Please provide the following details if possible or relevant:

- [1.1.1] the version of Ace impacted by the issue (as returned by the `ace -v` command).
- [10.16.0] the version of Node used to run Ace (as returned by the `node -v` command).
- [MacOS 10.14.6] your operating system and version.
- [] if the issue is a bug when running Ace: the error message as produced in the log file (you can enable debug logging with the `--verbose` option).
- [] if the issue is about the HTML report: the browser(s) and version(s) you used.
- [] if possible, let us know if you can share a sample input file to help us reproduce the issue.

After a crash of node.exe, the ace.log file in the folder ...\Daisy Ace\Log\ace.log is locked.
All future run of ace fails with permission error :
Throw er ; // Unhandled ‘error’ event
Error : EPERM : operation not pemitted, stat ‘C:\Users\VerifEpub\AppData\Local\Daisy Ace\Log\ace.log’

Would it be possible to give this ace.log a unique name per activation, so that next executions of ace are not locked ?

**Comment by rdeltour** [comment]
Thanks for the report. This is problematic indeed. We could either make try to figure out if the permission can be somehow reset, or else use a uniquely named log file as you suggest.

**Comment by danielweck** [comment]
Developer notes:
* The latest version v3.x of Winston ( https://github.com/winstonjs/winston ) is used in the "Ace App" (`ace-gui`) branch (https://github.com/daisy/ace/tree/feature/axe-runner-electron with PR https://github.com/daisy/ace/pull/236 ... and the corresponding deployment branch for AceApp: https://github.com/daisy/ace/tree/pr-merge/223+227 )
* I would suggest using a "log rotate" Winston transport in order to alleviate file-locking issues, such as https://github.com/winstonjs/winston-daily-rotate-file (this library automatically discards old log files, so that they do not grow indefinitely)
* We might need to adjust unit-tests that expect a single log file in a predictable location.

**Comment by danielweck** [comment]
Main code reference:
https://github.com/daisy/ace/blob/72047a2423c17bf05f6621d418e1dc0668eb0e83/packages/ace-logger/src/index.js#L49-L58

Note that we would have to capture stream termination (final flush) using the private `logStream` member instead of `__stream`:
https://github.com/daisy/ace/blob/72047a2423c17bf05f6621d418e1dc0668eb0e83/packages/ace-logger/src/index.js#L11-L38

https://github.com/winstonjs/winston-daily-rotate-file/blob/6f60117cd3fd9e5cee1d8a4a8f494df3bd4e270a/daily-rotate-file.js#L80-L94
vs.:
https://github.com/winstonjs/winston/blob/ae2335b49f4fb3e49f79801f5fc6da1159ed3133/lib/winston/transports/file.js#L50

See the reason for this hack:
https://github.com/winstonjs/winston#awaiting-logs-to-be-written-in-winston
https://github.com/winstonjs/winston/issues/1504#issuecomment-522106947
https://github.com/winstonjs/winston/issues/228#issuecomment-511731825

**Comment by danielweck** [comment]
Problem with "log rotate" Winston transport plugin (`winston-daily-rotate-file`): attempting to delete a locked file is probably as problematic as trying to write into it. Perhaps an easier-to-maintain option would be to implement an ad-hoc log rotation routine, not based on time/size, but on launched instances (each Ace execution would create its own UUID unique logfile). There would need to be a LRU Least Recently Used kind of logic to discard old log files, which would be unlikely to attempt access to locked / in-use files.

**Comment by danielweck** [comment]
Related (identical?) issue: https://github.com/daisy/ace/issues/286#issuecomment-538343254

**Comment by laudrain** [comment]
@danielweck this issue comes from wrong process killing when tentatively trying to stop the node.js freeze (see issue #286).
