### ISSUE TITLE
Ace with isseus, return code 0

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#287]
Please provide the following details if possible or relevant:

- [1.1.1] the version of Ace impacted by the issue (as returned by the `ace -v` command).
- [v10.16.3] the version of Node used to run Ace (as returned by the `node -v` command).
- [MacOS Mojave 10.14.6] your operating system and version.
- [see below] if the issue is a bug when running Ace: the error message as produced in the log file (you can enable debug logging with the `--verbose` option).
- [] if the issue is about the HTML report: the browser(s) and version(s) you used.
- [] if possible, let us know if you can share a sample input file to help us reproduce the issue.

See attached verbose log below : there are 2 issues detected in the file cover.xhtml.
The batch command lines:
```
ace $1.epub --force --verbose -o $1-ace -t $1-ace
echo $?
```
At the end, the value return as error code is 0, meaning no issue!
[9782017070986-ace.log](https://github.com/daisy/ace/files/3723889/9782017070986-ace.log)

Verbose log:

**Comment by laudrain** [comment]
My Mac OS is using bash:
```
HL040773:Extraits laudrain$ echo $SHELL
/bin/bash
```

**Comment by danielweck** [comment]
Thank you Luc.
I see that this bug report applies to the official `1.1.1` Ace release, published to NPM under the default `latest` tag.
The official `1.2.0-beta.2` release available under the `next` NPM tag (`npm install @daisy/ace@next`) includes some fixes which I suspect address the inconsistency you are observing.
Could you please check, and confirm / infirm?

**Comment by danielweck** [comment]
Ah, I've looked at the code and I understand the source of the problem. There is a configuration parameter called `return-2-on-validation-error` which is not exposed in the CLI "API" (i.e. arguments)

Ace `1.2.0-beta.2` code branch:

https://github.com/daisy/ace/blob/4cd99dfdcc471d943e5e06608ea8a32d67516ab2/packages/ace-cli-shared/src/defaults.json#L3

https://github.com/daisy/ace/blob/4cd99dfdcc471d943e5e06608ea8a32d67516ab2/packages/ace-cli-shared/src/index.js#L150-L152

Ace `1.1.1` code branch:

https://github.com/daisy/ace/blob/d5e7be6a084c766da1ec23f40622fb6dd403f323/packages/ace-cli/src/defaults.json#L3

https://github.com/daisy/ace/blob/d5e7be6a084c766da1ec23f40622fb6dd403f323/packages/ace-cli/src/index.js#L114-L119

**Comment by danielweck** [comment]
In other words:

* `1` exit code: "error" status when the CLI is invoked without the necessary arguments, or when the output directory exists and the `--force` argument was not specified, or in case of any thrown exception / unexpected error originating from some place in the Ace code stack.
* `0` exit code: "ok" status when the Ace validation completes successfully, and when it fails too! (because by default, `return-2-on-validation-error` = `false`)
* `2` exit code: "fail" status when Ace validation reports issues, AND when `return-2-on-validation-error` is set to`true`

So, we cannot break this existing behaviour, because it is possible that some batch scripts already rely on Ace exiting with code `0` both for "ok" and "fail" statuses. However, we MUST introduce a mechanism so that Ace CLI users can change the value of `return-2-on-validation-error` to `true`, either as an additional command line argument, and/or as a config file.

**Comment by danielweck** [comment]
Luc, please try the following:
https://daisy.github.io/ace/docs/config/#reference

**Comment by danielweck** [comment]
I am now closing this issue as the functionality already exists in the config file.
Luc, please re-open if you feel that there should be additional command line arguments to configure the same (I personally feel that the config file is a better approach, as we want to avoid the proliferation of possible CLI args)

**Comment by laudrain** [comment]
@danielweck thanks !
As I am on a new machine, I forgot the configuration file.
Works perfectly now.

**Comment by nxg** [comment]
I'd like to advocate reopening this.  It would be useful to be able to enable this behaviour (ie, exiting with an error on failure to validate) without a config file in `$HOME`.

I am using `ace` as part of a pipeline which builds the EPUB, and then checks the result.  At present, I run the [W3C epubcheck tool](https://github.com/w3c/epubcheck) and the build _fails_ if this returns non-zero.  I would like to then do the same with the `ace` tool, so want to enable `return-2-on-validation-error` so that it returns non-zero, and the build fails, on any conformance issues.  Since I want this to be self-contained – that is, entirely controlled by, in my case, a Makefile – I don't want this to depend on a configuration file elsewhere in the filesystem.

Suggestions:

  1. a new command-line option specific to this: I share your distaste for having too many such options, since the list of potential additions could be never-ending.
  1. a local config file: if `./config.json` is present, then use that.
  1. a command-line specifiable config file: `ace -C my-config.json ...`
  1. specify the configuration on the command line: `ace -C '{ "cli": {"return-2-on-validation-error":true }}' ...`.  That's clearly not something you'd want to type, but it's not particularly unnatural in a Makefile, and it avoids having to manage an extra config file even in the (temporary?) local directory.

The last three options would be generalisable to any future configuration options, without changing the set of command-line options.  My preference would be for the last option.

You could even potentially have the `-C` option do double-duty: if the value starts with `@` (ie `-C @my-config.json`), then read the configuration from the file; if not, then it is literal JSON (this is the same idiom as one sees in eg `rsync` and I think `curl`).
