### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by mjdunn1002** [daisy/ace#360]
Please provide the following details if possible or relevant:

- Version 1.1.3
- Node 14.16.0
- Windows 10 Enterprise; 21H1
- Error: Failed to check Content Document 'Kahle_ch34_Index.xhtml': Timeout :( 490000ms (490 seconds + 820700 nanoseconds) (489 seconds + 524136500 nanoseconds)

**Comment by danielweck** [comment]
Hello,

Would you mind trying the latest developer / test build which can be downloaded from the following link (please ignore the security warning message when installing the Windows app, this is only because only official releases are code-signed with the DAISY certificate):

https://github.com/daisy/ace-gui/releases

Alternatively, if you are comfortable with the command line / shell terminal, you may test with the latest version of Ace from NPM:

https://www.npmjs.com/package/@daisy/ace/v/latest

(`npm install @daisy/ace` should work, but depending on your system `npm install @daisy/ace --unsafe-perm=true` may work better from a MSDOS / PowerShell terminal "ran as administrator")

Please let me know if you would like me to try your EPUB at my end (the 8 minutes timeout indicate a serious failure, perhaps some network issue?)
