### ISSUE TITLE
Ace version of Ace variant in Ace report

### ISSUE THREAD

**Issue by LaZay** [daisy/ace#362]
The Ace report is indicating Ace version, which is very helpfull, as Ace is increasingly demanding.
But unlike the beginning of Ace story, there are now two coexisting Ace variants with different version numbers:
- Ace App  (last version = 1.1.3),
- Ace command line (last version = 1.2.2).

Would it be possible to specify which variant of the tool has generated an Ace report?
This would avoid panic, and misunterstanding in the Ace version that is installed!... ;-)

Thanks!

**Comment by LaZay** [comment]
EPUB Accessibility Report

Generated by DAISY Ace (1.2.2) on 2022-1-3 18:04:50
_could become:_
Generated by DAISY Ace command line (1.2.2) on 2022-1-3 18:04:50


Generated by DAISY Ace (1.1.3) on 2022-1-3 18:04:50
_could become:_
Generated by DAISY Ace Application (1.1.3) on 2022-1-3 18:04:50

**Comment by danielweck** [comment]
Fixed via https://github.com/daisy/ace/commit/a585612fdb6622383ff0926bf4b9b6a680a2aeec and https://github.com/daisy/ace-gui/commit/b4211ea002c6cb41ed319148cedd13d001a9680f
Example in English:
* Ace command line tool: `Generated by DAISY Ace (1.2.6-alpha.4) on 03/02/2022, 00:17:43`
* Ace App (GUI): `Generated by DAISY Ace (1.2.6-alpha.4) on 03/02/2022, 00:17:43 [Ace App v1.1.4-alpha.1]`

As you can see, the main information remains Ace "core" (CLI = command line interface) which actually drives the accessibility evaluation and the production of the JSON+HTML reports, but we append Ace App (GUI) information in order to disambiguate version numbers.
