### ISSUE TITLE
In node, call hangs indefinitely

### ISSUE THREAD

**Issue by zsofiamacho** [daisy/ace#429]
node: v18.20.4
npm: v10.7.0

When executing Daisy using
`/home/node_modules/@daisy/ace/bin/ace-puppeteer.js --outdir /daisyace --subdir  /timestamp/9781544380506_EPUB3.epub`

when checking one of the larger xhtmls, Daisy hangs forever and the process does not exit. (Not sure how to define "forever" here as I killed the process at one point.)

When checking the same epub in the GUI, it helpfully times out with a good error:
`Running Ace on C:\Users\Downloads\XXXXXXX_EPUB3.epub
Error: Failed to check Content Document 'sXXXXXXX.i7245.xhtml': Timeout :( 490000ms (490 seconds + 48599400 nanoseconds) (486 seconds + 148232100 nanoseconds)`

Cannot share problematic epub, and there are _many_ problematic epubs, not just a single file.

I am wondering: could the same behaviour, as in the UI, be implemented in puppeteer as well? 
Either an optional --timeout parameter that would let user specify how long to wait, or just the same behaviour: time out and stop the process. 

This is the same problem as already raised by others in #406

**Comment by danielweck** [comment]
hello, could you please try with the most recent build of Ace (command line tool) deployed at NPM under the tag "next" (as opposed to the default tag "latest" which is v1.3.2)
Could you please try with both the Puppeteer runner and the Electron one? (ace is an alias for ace-electron, ace-puppeteer is separate).
Could you please also use the most recent LTS (Long Term Support) version of NodeJS v22, or alternatively the maintenance release v20? (v18 is okay but I just want to make sure this isn't a factor)
Thank you very much.

**Comment by danielweck** [comment]
...you could also try the latest build of Ace App (Graphical User Interface) from https://github.com/daisy/ace-gui/releases , which is based on the latest build of Ace .

**Comment by danielweck** [comment]
PS: to be clear, using the Puppeteer runner instead of the default Electron one (i.e. launching ace-puppeteer instead of ace-electron or simply ace) is not recommended, as it is a slower runtime, and the web browser engine is not synchronised with Ace App (which is itself an Electron app, thus the perfect alignment).

**Comment by zsofiamacho** [comment]
Thank you @danielweck 
I confirm that this is working in ace-puppeteer 1.3.3-alpha.4
I get a timeout error, similarly to how I get one in the UI.
`error:   Ace HTML check error: Failed to check Content Document 's9781544384627.i7245.xhtml': Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.`

**Comment by danielweck** [comment]
I've not seen this error before. I was aware of timeouts due to large HTML structures, but this seems different. I would be happy to troubleshoot at my end if you are allowed to privately share an EPUB that exhibits this behaviour.

**Comment by danielweck** [comment]
Hello @zsofiamacho thank you for privately sharing a minimal EPUB which allowed me to reproduce the issue. On my fast computer using the latest revisions of Ace (not officially released yet, but already available for testers via the NPM package "next" tag https://www.npmjs.com/package/@daisy/ace/v/next ) ... checking your publication XHTML chapter takes 100+ seconds (approximately 2 minutes) with both the Puppeteer "runner" (deprecated) and Electron "runner" (recommended as it is also used in the Ace App GUI, not just in the Ace command line / CLI).

This is a huge amount of time spent by Deque Axe analysing your document. I believe this is because the DOM contains 43000 span elements, but I am not sure exactly what the performance bottleneck is in Deque Axe. My advice is to file an issue at https://github.com/dequelabs/axe-core to let their development team know about the problem.

The default Ace timeout for the Electron runner is over 8 minutes, which should give most consumer-grade computers plenty of time to check a heavy document. That being said, your "protocolTimeout" error is from the Puppeteer runner which has a default timeout of 180 seconds (in addition to the launch timeout of 30 seconds). I will add some code in Ace to increase the default 180 seconds.

https://github.com/puppeteer/puppeteer/blob/2b8ee62475b6614fc95b963c399b0bbad32e9e70/packages/puppeteer-core/src/common/ConnectOptions.ts#L88-L93

https://github.com/puppeteer/puppeteer/blob/2b8ee62475b6614fc95b963c399b0bbad32e9e70/packages/puppeteer-core/src/node/BrowserLauncher.ts#L85

**Comment by danielweck** [comment]
On MacOS and Linux, from the command line, it is quite simple to change the timeout values:

`ACE_TIMEOUT_INITIAL=10000 ACE_TIMEOUT_EXTENSION=480000 ace -l en -f -V -o ./output-folder/ book.epub`

On Windows the syntax depends on which terminal emulator is used (PowerShell vs. DOS vs. GitBash, for example). There are other ways to set environment variables too, at the system level instead of as temporary variables on the command line.

**Comment by danielweck** [comment]
To make things easier in Windows, I added the `-T` / `--timeout` command line argument which is essentially an override for `ACE_TIMEOUT_EXTENSION` which now defaults at 240 seconds (4 minutes).
